hmpps-auth:
  url: "http://localhost:8090/auth"

general-ledger-api:
  url: http://localhost:8084
  client:
    id: hmpps-prisoner-finance-general-ledger-api
    secret: clientsecret

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true